### ISSUE TITLE
Process stack of multiple images

### ISSUE THREAD

**Issue by csachs** [deepimagej/deepimagej-plugin#13]
So far there does not seem to be a way to process a stack (e.g. a time lapse acquistion) of images with the same model (processing frame by frame with the model, without passing multiple frames to it).
With the recent updates, scripting this, is sort of possible, however since for every frame the model gets reloaded, it has a very high overhead like this; hence it would be nice, if this would be added as a feature (furthermore, the model could remain loaded if the user wants to process multiple images with the same model).
(Concerning image stacks, it would be nice if the plugin would process the currently selected slice, like most other plugins do, currently it always processes the first. Maybe a dialog like in many other operations, prompting the user whether to process the current frame or all iteratively.)

Thanks, best regards, Christian
PS: I've seen there is a new repository `deepImagej-ij2-plugin` … will this be the main place of development now?

**Comment by esgomezm** [comment]
Hi @csachs 

Right now you can process a stack using a macro like in the Macro Example:
https://deepimagej.github.io/deepimagej/tutorials.html

> (Concerning image stacks, it would be nice if the plugin would process the currently selected slice, like most other plugins do, currently it always processes the first. Maybe a dialog like in many other operations, prompting the user whether to process the current frame or all iteratively.)

Yes, true. However, depending on the model and its input dimensions this could be problematic. We will make a thought! Thank you

> PS: I've seen there is a new repository deepImagej-ij2-plugin … will this be the main place of development now?

We will maintain both repositories, this one for IJ1 and deepImagej-ij2-plugin for IJ2. The updates are planned to be simultaneous. 

Thank you!
