### ISSUE TITLE
Error in nChannel 1

### ISSUE THREAD

**Issue by amostof** [deepimagej/deepimagej-plugin#18]
Hello,

When I use DeepImageJ on Fiji with this image, an [example](https://www.dropbox.com/t/RfjUjVvDo8BNXMQ1) provided by CellProfiler, it works fine, but when I use it with my own [images](https://www.dropbox.com/s/6kuvjpdrl85w0e0/3.tif?dl=0), it returns "Error in nChannel 1." Can you please help me with this problem?

Btw, thank you for the great software. I just found it yesterday and it can save me hours of work if I figure it out.

Best,
Amir

**Comment by esgomezm** [comment]
Hi @amostof 

Thank you for giving it a try and for your comments! 

The only problem is that your image is in RGB type, so it has three channels (Red, Green, Blue). For a quick try, you can convert it to 8 bits in Fiji, like the one in the example, by clicking on Image > Type > 8 bits. However, you will see that your image has a white scale bar of 400 microns. I'd strongly recommend you run the model on the raw image, without any scale bar or other artificial artifacts. 

Please, let me know if it works or ask for help if it still does not work!
Sincerely,
Esti

![gh](https://user-images.githubusercontent.com/43643518/116724977-9a83d980-a9e1-11eb-91bb-c28ba0022a68.png)

**Comment by amostof** [comment]
Thank you for taking the time to answer the question. Yes, that solves the problem. Looking at my image, what prebuilt bundle do you think might be the best to count the number of cells?
Best,
Amir

**Comment by esgomezm** [comment]
It is difficult to say as usually trained models do not work well on new data, especially coming from a different experiment or lab. What version of deepImageJ are you using? 
You could try [this one](https://bioimage.io/#/?id=deepimagej%2FUNet2DPancreaticSegmentation) and if you are using deepImageJ 2.1.7, you could also try [usiigaci](https://bioimage.io/#/?id=deepimagej%2FUsiigaci).

In case the models doesn't perform well (which is normal) I'd strongly recommend you to annotate some of your images, or patches of them and fine-tune the model on your data. You can use Google Colab to train the models. The notebook used for the Pancreatic Segmentation model is [this one](https://bioimage.io/#/?id=deepimagej%2Funet-pancreaticcellsegmentation). There are also solutions in [ZeroCostDL4Mic](https://github.com/HenriquesLab/ZeroCostDL4Mic).

I can help you with this last part.
