### ISSUE TITLE
Access to HPC Cluster

### ISSUE THREAD

**Issue by AndreZeug** [deepimagej/deepimagej-plugin#29]
Hi
can I configure Fiji + DeepImageJ on my local PC that it can access and use a HPC cluster for ML calculations? Pre- and postprocessing I would like to do on my local PC. The HPC cluster runs with Slurm.
Is this already implemented and described anywhere? Or would it be a new feature request? Or is this idea impossible at all.

I asked this already @image.sc (https://forum.image.sc/t/fiji-csbdeep-or-deepimagej-access-to-hpc-cluster/62483) but from the response it seems to be a rather challenging project.

**Comment by esgomezm** [comment]
Hey @AndreZeug 

Thank you for being so interested. I think the easiest way to do it is by calling deepImageJ from pyimagej as @carlosuc3m suggested in the forum. For this, you first need to have python installed. Second, you could store a Fiji installation already with deepImageJ inside. Finally, write a python script that calls it using pydeepimagej and run a macro that calls the deepImageJ plugin.

Yet another chance is to do something similar to [this](https://github.com/deepimagej/models/blob/master/setupDeepimagej.sh). I also point @oeway as he's involved in this.

What is not clear for me is whether you wanted to have the user interface of Fiji and deepImageJ or you want all the processes to be fully automatic and hidden for the user.

**Comment by esgomezm** [comment]
Dear @AndreZeug 

Unfortunately, those interactions are not available in deepImageJ directly. What might be possible is connecting Fiji to a cluster. Then you could also run deepImageJ using those resources, but that's something I would recommend you checking in Fiji's documentation as I'm not an expert on it.

Otherwise, Carlos' recommendation is the most straightforward solution

**Comment by xulman** [comment]
Hello @AndreZeug and all,

I've [replied on the forum to the original post linked above](https://forum.image.sc/t/fiji-csbdeep-or-deepimagej-access-to-hpc-cluster/62483/7).

In short here: There exists a project, a Fiji plugin, that connects on behalf of you to an HPC cluster and allows you to submit a job there (that means to ask for cluster resources and instruct the cluster what to execute when the resources are available). The executed thing could be a headless Fiji script (the .ijm macro or Jython or anything else Fiji can do) or recently a pure Python (non-Fiji) script.

I'm open to discussing it further, and even giving it a try, and/or help setting it up if you wanna try...

My two cents....
Vlado

PS: Thanks Arrate for pinging me.

**Comment by carlosuc3m** [comment]
Hello @AndreZeug and @xulman , I am coming back to this thanks to @xulman . He just reminded me of running models on HPC clusters within Fij. That should be now possible thanks to [JDLL](https://github.com/bioimage-io/JDLL).
JDLL can be used directly from scripts of Jython within Fiji, so there is nor need for a GUI. 

The commands to execute aany Tf, Pytorch or onnx models are simple (just a couple of lines). You can find an example of how to donwload a model, download an engine and execute a model and its corresponding pre- and post-processing here:
https://github.com/bioimage-io/JDLL/blob/main/scripts/example-run-pytorch-model-in-fiji.py
or here:
https://github.com/bioimage-io/JDLL/blob/main/scripts/example-run-tf2-model-in-fiji.py

There is also more information in the scripting docs:
https://github.com/bioimage-io/JDLL#quickstart-for-analystsscripting
