### ISSUE TITLE
Error loading PyTorch Model

### ISSUE THREAD

**Issue by DLF1794** [deepimagej/deepimagej-plugin#44]
Recently，I wanna use _LiveCellSegmentationBoundaryModel_ to analyze my cell images. However, when I click on Plugin>DeepImageJ>DeepImagJ Run, I got a popup warning: 
<img width="489" alt="1686663016742" src="https://github.com/deepimagej/deepimagej-plugin/assets/122598797/042130bd-db56-4214-a416-e95c476793bb">
Then, when I try to run on the example image, I got an popup again: 
<img width="435" alt="1686663153776" src="https://github.com/deepimagej/deepimagej-plugin/assets/122598797/b8b5bf62-3b13-4016-ad82-c39658d0ddc7">
I also got an error in console:
<img width="552" alt="1686662676426" src="https://github.com/deepimagej/deepimagej-plugin/assets/122598797/06f79e9a-7c1c-411d-b004-1a0e06cecadb">

What can I do?
Thanks for your helps!

**Comment by carlosuc3m** [comment]
Which version of DeepImageJ are you using? Could you please update it to the latest one (2.1.16)?
Also in which Operating System are you working?
REgards

**Comment by DLF1794** [comment]
I was using Fiji in windows and the version of DeepImageJ was already updated to V2.1.16 through Hepl>Update, but these problems remained.

**Comment by carlosuc3m** [comment]
The model works on my computer on Windows. 
Can you re-download the model please? Also can you check that the following .jar files are donwloaded into the "jars" folder inside the Fiji folder?
snakeyaml-1.21.jar
slf4j-simple-1.7.26.jar
slf4j-api-1.7.25.jar
pytorch-jni-1.13.1-0.21.0.jar
pytorch-engine-0.21.0.jar
jna-5.3.0.jar
gson-2.8.5.jar
commons-compress-1.20.jar
api-0.21.0.jar

If any of the previous JARs is not found or the version is the different, please delete it and download the corresponding one. HEre is the link to all the dependencies of deepImageJ: https://github.com/deepimagej/deepimagej-plugin/releases/download/2.1.16/dependencies_2116.zip

**Comment by DLF1794** [comment]
Thanks very much! 
I replaced all the JARS and re-download the model, this warning still remained.
![image](https://github.com/deepimagej/deepimagej-plugin/assets/122598797/95d1b843-b8fe-4473-9bf2-034bda0ab3f7)
When I tried to run the model, I got a new warning in the console.
<img width="722" alt="1686710886242" src="https://github.com/deepimagej/deepimagej-plugin/assets/122598797/5a487d37-32e6-4878-b9f1-7e34311a21da">
My Cuda version is 10.0 and Cudnn is V7.6.5 corresponding to Tensorflow 1.15.0 GPU. Is there something wrong with these versions?

**Comment by carlosuc3m** [comment]
PLease make sure that the API jar inside the jars folder is **api-0.21.0.jar**  as well as **pytorch-jni-1.13.1-0.21.0.jar** and **pytorch-engine-0.21.0.jar** and the other jars of other versions are removed. Also I forgot to mention that you also need to delete **pytorch-native-auto.jar**. 
If the error still persists please close Fiji, delete the folder `C:\Users\your_user\.djl.ai` and try again.

Cuda should be handled automatically by the plugin

**Comment by DLF1794** [comment]
Thanks!
I deleted pytorch-native-auto.jar and .dij.ai and updated the imageJ, and finally it worked.
By the way, can I get the cell counts using this model in Fiji?
