### ISSUE TITLE
Error loading tensorflow_saved_model_bundle

### ISSUE THREAD

**Issue by DLF1794** [deepimagej/deepimagej-plugin#46]
My deepimageJ was working fine before in the model _Widefield Super-resolution (GAN - TxRed)_ and _LiveCellSegmentationBoundaryModel_, but now, I suddenly get a popup warning that _Error loading tensorflow_saved_model_bundle_
<img width="293" alt="1687005194087" src="https://github.com/deepimagej/deepimagej-plugin/assets/122598797/cecbead9-d278-459d-9947-3979db35ecfa">
<img width="333" alt="1687005247493" src="https://github.com/deepimagej/deepimagej-plugin/assets/122598797/f17d453c-6bc8-46ac-8638-28b99fc8c191">
The screen shot of console
<img width="281" alt="1687005719069" src="https://github.com/deepimagej/deepimagej-plugin/assets/122598797/4ab8782e-6055-4c28-b103-adce28f45990">
What should I do to fix it?

**Comment by carlosuc3m** [comment]
Hello again @DLF1794 , It seems that you have just updated deepImageJ!. The relaease will be nnounced tomorrow. The engine management has changed. This means that tensorflow, pytorch and onnx should be downloaded once the open is opened for the first time. Hasn't it happened to you? You need o be connected to the internet.
The message you are receiving and the text saying "no engines installed, please install" means that imageJ has not found the engines.
How are you running deepImageJ? Where is it installed? It seems that the engines have been installed in the folder "C:\windows\system32\enignes", however they should have been installed inside the ImageJ folder.

**Comment by DLF1794** [comment]
As your helpful and kindly suggestion in Issue #44, deepimageJ worked steadily for a while. But one time when I was ready to use it again, It reminds me that  _unable to find an engines directory.Please create a folder called engines inside the imageJ/Fiji folder_. 
<img width="271" alt="1687141549728" src="https://github.com/deepimagej/deepimagej-plugin/assets/122598797/041eb83f-053a-413f-901c-47ff551933d7">
Then I opened the console and found the warning _engines jars directory is C:\WINDOWS\System32\engines_.  I remember, as your suggestion in issue44, there is no need for a folder named engines in the fiji.app folder. So I tried to create an engines folder in C:\WINDOWS\System32\. This is where the situation I described above comes in. 
I was confused because I didn't change any of deepimageJ's Settings after the first normal run, and these warnings just appeared out of nowhere.

**Comment by DLF1794** [comment]
Hello@carlosuc3m，thanks for your kindly suggestion! 
I updated deepImageJ just now, but the warning still remained.
<img width="372" alt="1687182455112" src="https://github.com/deepimagej/deepimagej-plugin/assets/122598797/93b3c8aa-fa5e-4c90-be76-22dfd716c326">
Is there anything I can try to fix it?

**Comment by carlosuc3m** [comment]
AS you see in the log window, the engines are being installed, please re-start deepimagej again and wait until the installation is finished.
