### ISSUE TITLE
CUDA versions

### ISSUE THREAD

**Issue by ryupath** [deepimagej/deepimagej-plugin#48]
My CUDA version is 11.8. How can I do gpu connection ?

**Comment by carlosuc3m** [comment]
The cuda connection is done automatically for the DL versions that are compatible with your cuda versions.
Here is a table witht the CUDA compatibilities:
https://github.com/bioimage-io/JDLL/wiki/VII.-GPU-configuration#requirements-for-the-connection-with-a-gpu
