### ISSUE TITLE
Error in execution: Pytorch

### ISSUE THREAD

**Issue by r95akshay** [deepimagej/deepimagej-plugin#51]
My operating system is Windows 11. To install the DeepImageJ (v3.0.3) in Fiji, I have followed the steps outlined in the [Manual installation page](https://deepimagej.github.io/download.html) and have also downloaded the [required dependencies (v3.0.3)](https://github.com/deepimagej/deepimagej-plugin/wiki#deepimagej-dependencies), including the ones for Pytorch in Windows OS. 
I then installed the BioImage Model (Plugins->DeepImageJ->DeepImageJ Install Model), NUCLEISEGMENTATIONBOUNDARYMODEL, which uses the Pytorch format. This is the model that I want to run on my images.
However, when I run the model, the following error pops up:
<img width="428" alt="image" src="https://github.com/user-attachments/assets/b7c1918a-4997-43c4-bba9-b4605ab3d654">
This is the snapshot of the console (FIJI is the renamed directory, where Fiji is installed):
<img width="590" alt="image" src="https://github.com/user-attachments/assets/e01f47f7-447b-4d2f-ac2e-18f0f0f858d8">

**Comment by carlosuc3m** [comment]
HEllo @r95akshay , first of all sorry for the delay answering!

The best way to install deepimageJ is through the Fiji update site.
Could you please open Fiji: Help>Update>add update site
Then look for deepimagej and click it.
The newest version of deepImageJ will be installed.

We are working on a big revamp of the plugin so it might not work immediately!
Please feel free to give some feedback!

REgards,
Carlos

**Comment by carlosuc3m** [comment]
Hello again @r95akshay ,
Does the new plugin that you get through the update site work for you?

**Comment by carlosuc3m** [comment]
This should be fixed now, please if you still have an error, reopen the issue.

@r95akshay
