### ISSUE TITLE
Build results in git repository grow git repository unnecessarily … + other suggestions

### ISSUE THREAD

**Issue by csachs** [deepimagej/deepimagej-plugin#9]
I've seen that you are currently adding all packaged ZIPs, along dependencies and old versions, into the repository. A fresh checkout is already 271 MB in size, and will likely grow dramatically over time.
May I suggest to follow standard git(hub) practices, and only check in source code into the repository; you can tag releases and attach build results via the 'Releases' function of github, where users can download your ready to use packages.
While the project is still in its early stages, you might benefit from force pushing a cleaner, more lightweight git repository (for cleanup of large files, tools like https://rtyley.github.io/bfg-repo-cleaner/ could be used), as the total size will always only grow over time.

Further suggestions would be:
- Automatic dependency management, e.g. via Ivy, or moving the build process to Maven, which seems to be the standard for the official ImageJ2/SciJava subprojects. They offer scaffold `pom.xml`s which can easily be extended.
- I would highly suggest to move over to TensorFlow 1.15, which follows 1.x API, but allows loading of models serialized with 2.0, which is the standard version since early October. (It should be backward compatible). I tested your plugin with TF 1.15 and it worked without issues.
- Chosing a `-gpu` build will give users the ability to use CUDA accelerated processing (with seamless CPU-fallback).

Thanks for the great work, and I'm looking forward to your publication.

**Comment by esgomezm** [comment]
Thank you @csachs for your comments!

> you can tag releases and attach build results via the 'Releases' function of github, where users can download your ready to use packages

The binary files have been removed already and a new release is available for the distribution of the plugin, thank you for the recommendation.

> Automatic dependency management, e.g. via Ivy, or moving the build process to Maven, which seems to be the standard for the official ImageJ2/SciJava subprojects. They offer scaffold pom.xmls which can easily be extended.

We are working on this. Actually @ctrueden has proposed a nice commit to solve this.

> I would highly suggest to move over to TensorFlow 1.15, which follows 1.x API, but allows loading of models serialized with 2.0, which is the standard version since early October. (It should be backward compatible). I tested your plugin with TF 1.15 and it worked without issues.

This will be introduced very soon. We are doing different trials to manage tensorflow versions and be synchronized with the publication where all details are given :)

**Comment by csachs** [comment]
Thanks for the feed back, sounds great!
Concerning PR #11 , be aware tho' that merely merging it will not slim down the repository, which will remain at ~195 MB.

**Comment by ctrueden** [comment]
Right, PR #10 is just the minimum needed to build from the command line at all. I agree with @csachs that switching to Maven would be better. Would you be interested in a PR for that? I might have time...

**Comment by csachs** [comment]
For the long term viability of this git repository, I'd still suggest slimming it down by removing ZIP and JAR files in the history using [BFG](https://rtyley.github.io/bfg-repo-cleaner/), e.g. like follows:

```bash
% wget "https://search.maven.org/classic/remote_content?g=com.madgag&a=bfg&v=1.13.0" -O bfg-1.13.0.jar
% git clone --mirror https://github.com/deepimagej/deepimagej-plugin
% du -hd0 deepimagej-plugin.git
194M	deepimagej-plugin.git
% java -jar bfg-1.13.0.jar -D '*.{jar,zip}' deepimagej-plugin.git
% cd deepimagej-plugin.git && git reflog expire --expire=now --all && git gc --prune=now --aggressive && cd ..
% du -hd0 deepimagej-plugin.git
328K	deepimagej-plugin.git
```

Would change the repository size from 194 MB to 328 KB ... keep a backup tho', and double check that everything worked correctly; by rewriting the history, all currently pulled repositories become  commit/merge incompatible with this one, so it should be done as early as possible, ideally with all developers aware of the change (maybe merge PR #10 first) …

**Comment by ctrueden** [comment]
@csachs Tangentially: have you seen [jgo](https://github.com/scijava/jgo)? With it, you can run Java code from Maven artifacts without downloading them explicitly. To run BFG:
```
jgo com.madgag:bfg:1.13.0:com.madgag.git.bfg.cli.Main
```
(Normally you can leave off the main class if the JAR has a Main-Class in its manifest, but it looks like BFG has some weird manifest entries.)

**Comment by csachs** [comment]
@ctrueden very nice! Wasn't aware yet, but this looks like a gift from heaven for many tasks!

**Comment by esgomezm** [comment]
> Right, PR #10 is just the minimum needed to build from the command line at all. I agree with @csachs that switching to Maven would be better. Would you be interested in a PR for that? I might have time...

Many thanks for PR #10 . It is already merged :) yes, we are interested! it would be very helpful if you had some suggestions to switch to Maven

**Comment by esgomezm** [comment]
> For the long term viability of this git repository, I'd still suggest slimming it down by removing ZIP and JAR files in the history using [BFG](https://rtyley.github.io/bfg-repo-cleaner/), e.g. like follows:
> 
> ```shell
> % wget "https://search.maven.org/classic/remote_content?g=com.madgag&a=bfg&v=1.13.0" -O bfg-1.13.0.jar
> % git clone --mirror https://github.com/deepimagej/deepimagej-plugin
> % du -hd0 deepimagej-plugin.git
> 194M	deepimagej-plugin.git
> % java -jar bfg-1.13.0.jar -D '*.{jar,zip}' deepimagej-plugin.git
> % cd deepimagej-plugin.git && git reflog expire --expire=now --all && git gc --prune=now --aggressive && cd ..
> % du -hd0 deepimagej-plugin.git
> 328K	deepimagej-plugin.git
> ```
> 
> Would change the repository size from 194 MB to 328 KB ... keep a backup tho', and double check that everything worked correctly; by rewriting the history, all currently pulled repositories become commit/merge incompatible with this one, so it should be done as early as possible, ideally with all developers aware of the change (maybe merge PR #10 first) …

We'll check it these days! Thank you very much, this is really helping us to learn and improve :)
